### ISSUE TITLE
wont run 

### ISSUE THREAD

**Issue by XanuduBuster** [AVVERSION/DiscordAI#1]
here is the console log below:
```
hiren@smasnug ➜ /mnt/nas-1pb/repo/avversion/DiscordAI (main) $ mv .env.example .env
hiren@smasnug ➜ /mnt/nas-1pb/repo/avversion/DiscordAI (main) $ nano .env
hiren@smasnug ➜ /mnt/nas-1pb/repo/avversion/DiscordAI (main) $ pip install -r requirements.txt
Requirement already satisfied: aiohttp==3.8.6 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 1)) (3.8.6)
Requirement already satisfied: aiosignal==1.3.1 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 2)) (1.3.1)
Requirement already satisfied: async-timeout==4.0.3 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 3)) (4.0.3)
Requirement already satisfied: attrs==23.1.0 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 4)) (23.1.0)
Requirement already satisfied: certifi==2023.7.22 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 5)) (2023.7.22)
Collecting charset-normalizer==3.3.1 (from -r requirements.txt (line 6))
  Downloading charset_normalizer-3.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (33 kB)
Requirement already satisfied: discord-protos==0.0.2 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 7)) (0.0.2)
Requirement already satisfied: discord.py-self==2.0.0 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 8)) (2.0.0)
Requirement already satisfied: frozenlist==1.4.0 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 9)) (1.4.0)
Requirement already satisfied: gpt4all==2.0.1 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 10)) (2.0.1)
Requirement already satisfied: idna==3.4 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 11)) (3.4)
Requirement already satisfied: multidict==6.0.4 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 12)) (6.0.4)
Requirement already satisfied: protobuf==4.24.4 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 13)) (4.24.4)
Requirement already satisfied: requests==2.31.0 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 14)) (2.31.0)
Requirement already satisfied: tqdm==4.66.1 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 15)) (4.66.1)
Requirement already satisfied: urllib3==2.0.7 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 16)) (2.0.7)
Requirement already satisfied: yarl==1.9.2 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 17)) (1.9.2)
Requirement already satisfied: dotenv==0.0.5 in /home/hiren/.local/lib/python3.10/site-packages (from -r requirements.txt (line 18)) (0.0.5)
Downloading charset_normalizer-3.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (139 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 139.2/139.2 kB 1.2 MB/s eta 0:00:00
Installing collected packages: charset-normalizer
  Attempting uninstall: charset-normalizer
    Found existing installation: charset-normalizer 3.3.0
    Uninstalling charset-normalizer-3.3.0:
      Successfully uninstalled charset-normalizer-3.3.0
Successfully installed charset-normalizer-3.3.1

[notice] A new release of pip is available: 23.3 -> 23.3.1
[notice] To update, run: python -m pip install --upgrade pip
hiren@smasnug ➜ /mnt/nas-1pb/repo/avversion/DiscordAI (main) $ python main.py 
Traceback (most recent call last):
  File "/mnt/nas-1pb/repo/avversion/DiscordAI/main.py", line 7, in <module>
    from gpt4all import GPT4All
  File "/home/hiren/.local/lib/python3.10/site-packages/gpt4all/__init__.py", line 1, in <module>
    from .gpt4all import Embed4All, GPT4All  # noqa
  File "/home/hiren/.local/lib/python3.10/site-packages/gpt4all/gpt4all.py", line 18, in <module>
    from . import pyllmodel
  File "/home/hiren/.local/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 42, in <module>
    llmodel = load_llmodel_library()
  File "/home/hiren/.local/lib/python3.10/site-packages/gpt4all/pyllmodel.py", line 32, in load_llmodel_library
    lib = ctypes.CDLL(str(MODEL_LIB_PATH / f"libllmodel.{ext}"))
  File "/usr/local/python/3.10.8/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /home/hiren/.local/lib/python3.10/site-packages/gpt4all/llmodel_DO_NOT_MODIFY/build/libllmodel.so)
hiren@smasnug ➜ /mnt/nas-1pb/repo/avversion/DiscordAI (main) $ 
```

it wont run for some reason, it looks like its encountering an error related to the GLIBCXX version not being found. it seems that the required version GLIBCXX_3.4.29 is not available. 

is it cuz i am running from a remote drive (1 petabyte asustor nas) or my current (sort of broken) ubuntu 23.04 installation?

i did put the token (as above of the console log) but it didn't work.

**Comment by foglomon** [comment]
The program was mainly built on the Ubuntu 22.04 LTS (Jammy). This isn't an issue with the code. It's a missing file in some versions of Ubuntu. It's essential for GCC to run the GPT4All library. I suggest you Google the file name and find a way to get it on your system. I would create a workaround or add instructions on how to get the file in the near future. If you find one, please be free to add a pull request and we would be more than thankful! Thank you for trying out the bot!

**Comment by XanuduBuster** [comment]
@AVVERSION Tried on Ubuntu 22.04 LTS and 20.04 LTS but still I am having the same issue tho i think its the container issue, didnt try vm cuz kvm/qemu is broken in my system..

**Comment by foglomon** [comment]
It was made on Ubuntu 22.04 LTS with the additional GLIBCXX file missing. It was installed separately. I have updated the documentation on links to download it. You may check it there.

**Comment by XanuduBuster** [comment]
@AVVERSION Tried it again with the files separately installed, it did execute properly however it said error cant login and i checked and found the account i was trying got banned, oops

**Comment by foglomon** [comment]
That shouldn't happen with a normal account by default. It could be because of a mismatched token. Did you put in a bot token with self-bot enabled or a normal account token with self bot disabled?
